error: this async expression only awaits a single future
  --> tests/ui/redundant_async_block.rs:13:13
   |
LL |     let x = async { f.await };
   |             ^^^^^^^^^^^^^^^^^
   |
   = note: `-D clippy::redundant-async-block` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::redundant_async_block)]`
help: you can reduce it to
   |
LL |     let x = f;
   |             ~

error: this async expression only awaits a single future
  --> tests/ui/redundant_async_block.rs:20:16
   |
LL |     let fut2 = async { fut1.await };
   |                ^^^^^^^^^^^^^^^^^^^^
   |
help: you can reduce it to
   |
LL |     let fut2 = fut1;
   |                ~~~~

error: this async expression only awaits a single future
  --> tests/ui/redundant_async_block.rs:24:16
   |
LL |     let fut2 = async move { fut1.await };
   |                ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: you can reduce it to
   |
LL |     let fut2 = fut1;
   |                ~~~~

error: this async expression only awaits a single future
  --> tests/ui/redundant_async_block.rs:27:15
   |
LL |     let fut = async { async { 42 }.await };
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: you can reduce it to
   |
LL |     let fut = async { 42 };
   |               ~~~~~~~~~~~~

error: this async expression only awaits a single future
  --> tests/ui/redundant_async_block.rs:43:5
   |
LL |     async move { fut.await }
   |     ^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: you can reduce it to
   |
LL |     fut
   |

error: this async expression only awaits a single future
  --> tests/ui/redundant_async_block.rs:56:5
   |
LL |     async move { fut.await }
   |     ^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: you can reduce it to
   |
LL |     fut
   |

error: this async expression only awaits a single future
  --> tests/ui/redundant_async_block.rs:61:5
   |
LL |     async { f.await }
   |     ^^^^^^^^^^^^^^^^^
   |
help: you can reduce it to
   |
LL |     f
   |

error: this async expression only awaits a single future
  --> tests/ui/redundant_async_block.rs:84:5
   |
LL |     async { async { f().await + 1 }.await }
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: you can reduce it to
   |
LL |     async { f().await + 1 }
   |

error: this async expression only awaits a single future
  --> tests/ui/redundant_async_block.rs:147:13
   |
LL |             async { async { 42 }.await }
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
LL |     mac!()
   |     ------ in this macro invocation
   |
   = note: this error originates in the macro `mac` (in Nightly builds, run with -Z macro-backtrace for more info)
help: you can reduce it to
   |
LL |             async { 42 }
   |

error: this async expression only awaits a single future
  --> tests/ui/redundant_async_block.rs:167:13
   |
LL |             async { async { $e }.await }
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
LL |     mac!(42)
   |     -------- in this macro invocation
   |
   = note: this error originates in the macro `mac` (in Nightly builds, run with -Z macro-backtrace for more info)
help: you can reduce it to
   |
LL |             async { $e }
   |

error: aborting due to 10 previous errors

